#!/usr/bin/env bash

set -euo pipefail

die()
{
  echo "$@" >&2
  exit 1
}

[ $# -eq 7 ] || die "usage: $0 in.pdf signature.image x_offset_cm y_offset_cm scale page out.pdf"

in_pdf=$1
shift
in_signature=$1
shift
x_offset=$1
shift
y_offset=$1
shift
scale=$1
shift
page=$1
shift
out_pdf=$1
shift

tmp=$(mktemp -d)
trap "rm -rf $tmp" EXIT

signature=$tmp/sig.pdf
stamp=$tmp/stamp.pdf
blank=$tmp/blank.pdf
result=$tmp/result.pdf

echo "convert and resize signature"
pdfjam --quiet --paper 'a4paper' \
  --scale $scale --offset "${x_offset}cm ${y_offset}cm" \
  --outfile $signature $in_signature

echo "extract number of pages"
num_pages=$(pdftk $in_pdf dump_data | grep NumberOfPages | sed -e 's/.* //')
echo "$in_pdf has $num_pages pages"

echo "create pdf stamp for page $page"
convert xc:none -page A4 $blank
n_blanks()
{
  yes $blank | head -n$1
}
pdftk $(n_blanks $((page - 1))) $signature $(n_blanks $((num_pages - page)))\
  cat output $stamp

echo "stamp file $in_pdf"
pdftk $in_pdf multistamp $stamp output $result
mv $result $out_pdf
echo "created file $out_pdf"
